name: Run Python Script

on:

  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        API_URL_SPPI_IVP_RF: ${{ secrets.API_URL_SPPI_IVP_RF }}
        PROXY_HTTPS_URL: ${{ secrets.PROXY_HTTPS_URL }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        python your_script.py
